name: SonarQube Scan para ProgRedes 2023.1

on:
  push:                                                                                                            
    branches:                                                                                                      
      - main                                                                                                       
                                                                                                                   
jobs:
  sonar:
    name: Run SonarScanner on Self-Hosted Runner
    runs-on: [self-hosted, sonarqube]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Rodar SonarScanner local
        env:
          SONAR_PROJECT_KEY: ${{ github.repository }}
          SONAR_USER_TOKEN: ${{ secrets.SONARQ_USER_TOKEN }}
          # o home do host é na visao do scanner          
          SONAR_HOST_URL: ${{ vars.SONARQ_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=$SONARQ_PROJECT_KEY \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONARQ_HOST_URL \
            -Dsonar.login=$SONARQ_USER_TOKEN
